# docker build -t xoxo-dashboard -f Dockerfile.production .
# docker run --rm -p 3000:3000 --name xoxo-dashboard -ti xoxo-dashboard
FROM node:12
WORKDIR /usr/src/app
COPY package.json .
COPY .env.production .env
RUN npm install --silent
RUN npm install react-scripts@3.2.0 -g --silent
COPY public .
COPY src .
EXPOSE 3000
CMD ["npm", "start"]